services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: datavision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - datavision-network

  backend-java:
    build: ./backend-java
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/datavision
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
      - minio-init
      - ml-service
    networks:
      - datavision-network

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - minio-init
    networks:
      - datavision-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - datavision-network

  minio-init:
    image: busybox
    command: sh -c "chmod +x /minio-setup.sh && /minio-setup.sh"
    volumes:
      - ./minio-setup.sh:/minio-setup.sh
    depends_on:
      - minio
    networks:
      - datavision-network

volumes:
  db-data:
  minio_data:

networks:
  datavision-network:
    driver: bridge
