services:
  db:
    container_name: db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: datavision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - datavision-network

  backend-java:
    container_name: backend-java
    build: ./backend-java
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/datavision
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - minio-init
      - ml-service
    networks:
      - datavision-network

  ml-service:
    container_name: ml-service
    build: ./ml-service
    ports:
      - "8000:8000"
    environment:
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin12345
      - MINIO_BUCKET_NAME=datavision-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - minio-init
    networks:
      - datavision-network

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - datavision-network

  minio-init:
    container_name: minio-init
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until /usr/bin/mc alias set local http://minio:9000 admin admin12345; do
        sleep 1;
      done;
      echo 'MinIO is up. Creating bucket...';
      /usr/bin/mc mb local/datavision-data --ignore-existing;
      /usr/bin/mc anonymous set public local/datavision-data;
      echo 'Bucket and policy set successfully.';
      "
    depends_on:
      - minio
    networks:
      - datavision-network

volumes:
  db-data:
  minio_data:

networks:
  datavision-network:
    driver: bridge
